---
output:
    pdf_document:
      citation_package: natbib
      df_print: tibble
      fig_caption: yes
      keep_tex: no
      template: "../template/latex-ms.tex"
title: 'Introdução à análise de dados'
author:
- affiliation: National Institute for Space Research (INPE), Brazil
  name: Felipe Carvalho
- affiliation: National Institute for Space Research (INPE), Brazil
  name: Felipe Menino
date: "`r format(Sys.time(), '%B %d, %Y')`"
endnote: false
fontfamily: mathdesign
fontfamilyoptions: adobe-utopia
fontsize: 11pt
graphics: true
header-includes:
 \usepackage{float}
 \usepackage[utf8]{inputenc}
 \usepackage[T1]{fontenc}
 \usepackage{multirow}
 \usepackage{xcolor}
 \usepackage{hyperref}
mathtools: true
bibliography: ./template/references-sits.bib
abstract: A aplicação dos conceitos vistos no minicurso de introdução à análise de dados é extremamente importante para a fixação dos conceitos. Desta forma, esta lista de exercícios busca criar situações que ajudem o aluno na aplicação e fixação de tais conceitos.
---

# 1. Contexto

Atualmente na \textbf{Google Play Store} existem milhares de aplicativos, com as mais variadas características. Um conjunto de dados disponibilizados no \href{https://www.kaggle.com/}{Kaggle} traz informações gerais sobre 10 mil aplicativos disponibilizados na loja.

O interessante deste conjunto é tentar fazer verificações dos tipos mais populares de aplicativos, para quem sabe, ao começar um novo aplicativo, você já saber qual tendência seguir.

Para esta análise, um conjunto amostral de 1000 registros será utilizado, porém, encorajamos você a depois que finalizar a atividade, acessar a \href{https://www.kaggle.com/lava18/google-play-store-apps}{página dos dados} e fazer a análise com todos os dados.

# 2. Atividade

Como apresentado ao longo das atividades do curso, a analise de dados é basicamente uma atividade utilizada para responder perguntas através de diferentes métodos de tratamento e manipulação dos dados.

Com base nisto, faça a análise do conjunto de dados \textbf{MIAD003}, que está no repositório do minicurso, dentro do diretório \textbf{atividades}.

Com este conjunto de dados, responda as seguintes perguntas:

\begin{enumerate}
    \item Qual a categoria de aplicativo mais comum na \textbf{Google Play Store} ?
    \item Qual a categoria dos aplicativos com maior média de avaliações ?
    \item A maior quantidade de \textit{reviews} pertence a qual aplicativo ?
    \item Há mais aplicativos pagos ou grátis neste conjunto de dados ?
\end{enumerate}
  
\newpage

## \textit{\textbf{Dicas}}

Abaixo uma tabela com a relação de funções que podem ser úteis para a solução dos exercícios propostos

```{r, tab1, echo=FALSE}
  library(kableExtra)

  tabela <- tibble::tibble(`Descrição` = c(
    "Leitura de dados", 
    "Agrupamento", 
    "Filtro", 
    "Desvio padrão", 
    "Média",
    "Mínino",
    "Máximo"),
    `R` = c("readr::read_csv()",
            "dplr::group_by()",
            "dplyr::filter()",
            "stats::sd()",
            "mean()",
            "min()",
            "max()"),
    `Python` = c("pd.read_csv()",
                 "pd.DataFrame.groupby()",
                 "pd.DataFrame[Condição]",
                 "pd.DataFrame.std()",
                 "pd.DataFrame.mean()",
                 "pd.DataFrame.min()",
                 "pd.DataFrame.max()"));
  knitr::kable(tabela, format = "markdown")
```
