# Introdução ao Python `r emo::ji("rocket")`

Python é uma linguagem multiparadigma, com uma sintaxe muito simples que permite ao programador focar no problema e deixar de lado questões da linguagem. 
Esta é uma linguagem amplamente utilizada em diversos áreas, por conta principalmente das milhares de bibliotecas que a linguagem possui, todas elas distribuidas pela comunidade incrível que a linguagem possui `r emo::ji("heart")`

Neste introdução, o foco será a aplicação da linguagem Python na manipulação e tratamento de dados, utilizando como base as bibliotecas Pandas e ao Matplotlib.

Você pode estar se perguntando o motivo da utilização destas bibliotecas, e a respostas é bem simples, Python é uma linguagem para uso geral, assim, suas funções nativas não tem foco em uma função específica, como ocorre em linguagem como R, que já tem um foco em uma área específica (No caso do R, em análises estatísticas, como descrito no capítulo 2 deste material).

Vamos começar !

## Introdução ao Pandas `r emo::ji("panda_face")`

Como forma de iniciar, vamos começar entendendo o que é a biblioteca Pandas e qual seu objetivo geral, para isto, vejamos a definição feita pelo próprio site do projeto.

> pandas é uma biblioteca open source, licenciada pelo BSD, que fornece estruturas de dados de alto desempenho e fáceis de usar e ferramentas de análise de dados para a linguagem de programação Python.

Veja então que, tudo o que é necessário para a realização da maioria dos casos de análise de dados utilizando a linguagem Python, irão, bem provavelmente, trabalhar com esta biblioteca.

Para que se tenha uma ideia, o pandas pode ser aplicado em análises envolvendo:

- Finanças;
- Análise estatística;
- Ciência social;
- Além de diversas outras áreas de ciências e engenharia.

Isto tudo, por contar com diversas funções e estruturas de dados que facilitam os processos de análise, por falar nestas funções e estruturas, no próximo tópico, vamos discutir um pouco mais sobre as principais presentes no pandas. 

## Estruturas de dados

As duas principais estruturas de dados presentes no pandas são:

- Series;
- DataFrames.

Vejamos as principais características de cada uma delas

### Series

As `Series` são estruturas de dados unidimensionais, que contam com diversos métodos para a manipulação de dados.
Pode-se entender que as `Series` são estruturas de dados simples, assim como as listas padrões da linguagem Python, com uma pequena diferença, para cada item dentro de uma `Series` tem-se indices, estes podendo ser valores numéricos ou texto.

Vamos começar a utilização, para facilitar o entendimento.

```{r}
# Estes comandos não devem ser executados em seu terminal
library(reticulate) 
use_python("/home/felipe/anaconda3/bin/python")
```

Para iniciar, vamos criar um simples `Series` e colocar dentro de uma variável. Para isto, importando a biblioteca pandas, e passamos para ela o 'apelido' de `pd`.

Em seguida, criar uma `Series` simples, passando como parâmetro de entrada uma lista com três valores, veja:

```{python}
import pandas as pd

s = pd.Series([1, 2, 3]); print(s)
```

É interessante notar que, cada uma das linhas, tem associado um index (Pode ser visto do lado esquerdo dos valores), e isto permite a recuperação dos valores através destes index. Você pode fazer uma analogia a forma com que você recupera os valores em um dicionário em Python, a diferença aqui é que, esta é uma estrutura de dados de alto desempenho, além de que, estas estruturas são otimizadas para fazer a melhor utilização de memória possível.

```{python}
print(s[0]) # Recupera o valor do index com nome 0
```

Por falar em dicionários, estes podem ser facilmente transformados em `Series`, veja:

```{python}
dicto = {
  'faculdade': 'Fatec',
  'nota': 10 
}

dicto_s = pd.Series(dicto); print(dicto_s)
```

Após a conversão, o uso é basicamente o mesmo do dicionário, porém com os benefícios já citados. Além do que já foi dito sobre os `Series`, é importante lembrar que, estas estruturas de dados possuem diversos métodos para facilitar a manipulação e entendimento dos dados, vamos a alguns destes métodos

Caso queira-se uma rápida descrição de seus dados, é possível obter um resumo estatístico

```{python}
data = pd.Series([1, 2, 3, 4, 5])

print(data.describe())
```

Este tipo de comando pode te ajudar a entender os dados que você está analisando.

Além disto, você pode ter necessidades como buscas dentro do conjunto de dados, existem diversas maneiras de fazer isto com pandas, mas uma forma simples e intuitiva é a utilização de indexação booleana, onde basicamente uma expressão lógica é passada como ponto para indexação.

```{python}
data_m_tres = data[data > 3] # Devolve todos os valores dentro da Serie que são maiores que 3
print(data_m_tres)
```


### Dataframes

## Introdução ao Matplotlib `r emo::ji("bar_chart")`